apiVersion: v1
kind: Service
metadata:
  name: db-frontend
  namespace: db-stack
  labels:
    app: db-frontend
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: db-frontend