apiVersion: v1
kind: Secret
metadata:
  name: db-app-secret
  namespace: db-stack
type: Opaque
# Use stringData for readability. Kubernetes will convert to base64 automatically.
stringData:
  DB_USER: demo
  DB_PASSWORD: demo