---
apiVersion: v1
kind: Secret
metadata:
  name: db-cloudflared-token
  namespace: db-stack
type: Opaque
stringData:
  token: "eyJhIjoiMjMwZGE2MTk5ZTU4ODk2MDEzYzlhY2M5ZDBlZTg3NjQiLCJ0IjoiM2ZhNWE4MGEtNGJmOC00MDcwLTgyM2QtMTY5NGM4NTdiMzEzIiwicyI6Ik56QmhNalV6TjJJdE5UVXdPQzAwTVRabUxXRm1ZV0V0TjJOaU5XWTRORGd6T1RZNCJ9"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-cloudflared
  namespace: db-stack
  labels:
    app: db-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-cloudflared
  template:
    metadata:
      labels:
        app: db-cloudflared
    spec:
      containers:
        - name: db-cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: db-cloudflared-token
                  key: token
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
